import { Tree, type TreeOf } from "@/components/fields/CheckboxGroup"
import { DirectTreeCard, Generator, Leaf, PartialCard } from "./shared"

// prettier-ignore
type BaseKanaNames =
  | "a" | "i" | "u" | "e" | "o" | "ka" | "ki" | "ku" | "ke" | "ko" | "sa"
  | "shi" | "su" | "se" | "so" | "ta" | "chi" | "tsu" | "te" | "to" | "na"
  | "ni" | "nu" | "ne" | "no" | "ha" | "hi" | "fu" | "he" | "ho" | "ma" | "mi"
  | "mu" | "me" | "mo" | "ya" | "yu" | "yo" | "ra" | "ri" | "ru" | "re" | "ro"
  | "wa" | "wo" | "n"

type WiWeKanaNames = "wi" | "we"

// prettier-ignore
type DakutenKanaNames =
  | "ga" | "gi" | "gu" | "ge" | "go" | "za" | "ji" | "zu" | "ze" | "zo" | "da"
  | "ji2" | "zu2" | "de" | "do" | "ba" | "bi" | "bu" | "be" | "bo" | "pa" | "pi"
  | "pu" | "pe" | "po"

type LittleKanaNames = "xya" | "xyu" | "xyo"

function kanaList(
  type: "Hiragana" | "Katakana",
  kana: { [romaji: string]: string },
): RawTree {
  return Object.fromEntries(
    Object.entries(kana).map(([romaji, kana]) => [
      romaji,
      new DirectTreeCard(
        romaji,
        romaji,
        (
          <>
            <span class="font-sans">{kana}</span>
            <span class="font-serif">{kana}</span>
            <span class="font-mono">{kana}</span>
          </>
        ),
        ["Japanese", type],
        1 / 30,
      ),
    ]),
  )
}

function kanaTree(
  type: "Hiragana" | "Katakana",
  base: Record<BaseKanaNames, string>,
  wiwe: Record<WiWeKanaNames, string>,
  dakuten: Record<DakutenKanaNames, string>,
  little: Record<LittleKanaNames, string>,
): RawTree {
  const { xya, xyo, xyu } = little
  const { ki, shi, chi, ni, hi, mi, ri } = base
  const { gi, ji, bi, pi } = dakuten
  return {
    Basic: kanaList(type, { ...base, ...wiwe }),
    Dakuten: kanaList(type, dakuten),
    Combination: kanaList(type, {
      kya: ki + xya,
      kyu: ki + xyu,
      kyo: ki + xyo,
      gya: gi + xya,
      gyu: gi + xyu,
      gyo: gi + xyo,
      sha: shi + xya,
      shu: shi + xyu,
      sho: shi + xyo,
      ja: ji + xya,
      ju: ji + xyu,
      jo: ji + xyo,
      cha: chi + xya,
      chu: chi + xyu,
      cho: chi + xyo,
      nya: ni + xya,
      nyu: ni + xyu,
      nyo: ni + xyo,
      hya: hi + xya,
      hyu: hi + xyu,
      hyo: hi + xyo,
      bya: bi + xya,
      byu: bi + xyu,
      byo: bi + xyo,
      pya: pi + xya,
      pyu: pi + xyu,
      pyo: pi + xyo,
      mya: mi + xya,
      myu: mi + xyu,
      myo: mi + xyo,
      rya: ri + xya,
      ryu: ri + xyu,
      ryo: ri + xyo,
    }),
  }
}

function kanaRead(
  kana: { [romaji: string]: string } & ({ ン: string } | { ん: string }),
): Node {
  const nn = "ん" in kana ? "ん" : "ン"
  const { ん, ン, ...rest } = kana

  function count(n: number): Node {
    return new Generator((id = "") => {
      if (!id) {
        for (let i = 0; i < n; i++) {
          id += random(Object.keys(rest))
          if (
            !(id.endsWith("ん") || id.endsWith("ン")) &&
            Math.random() < 0.25
          ) {
            i++
            if (i < n) {
              id += nn
            }
          }
        }
      }

      return new PartialCard(
        id,
        id,
        (id.match(/.[ゃゅょャュョ]?/g) || []).map((c) => kana[c]).join(""),
        ["Japanese", "Kana"],
        id,
      )
    }, 10)
  }

  return {
    "2 Characters": count(2),
    "3 Characters": count(3),
    "5 Characters": count(5),
    "8 Characters": count(8),
    "12 Characters": count(12),
  }
}

function each<T>(
  names: T[],
  card: (value: T) => Node,
  name: (x: T) => string = String,
): RawTree {
  return Object.fromEntries(names.map((x) => [name(x), card(x)]))
}

type RawTree = TreeOf<Leaf>

type Node = RawTree | Leaf

function random<T>(x: readonly T[]): T {
  if (x.length == 0) {
    throw new RangeError("Array must not be empty.")
  }

  return x[Math.floor(x.length * Math.random())]!
}

export const tree = new Tree<Leaf>(
  {
    Japanese: {
      Hiragana: {
        ...kanaTree(
          "Hiragana",
          {
            a: "あ",
            i: "い",
            u: "う",
            e: "え",
            o: "お",
            ka: "か",
            ki: "き",
            ku: "く",
            ke: "け",
            ko: "こ",
            sa: "さ",
            shi: "し",
            su: "す",
            se: "せ",
            so: "そ",
            ta: "た",
            chi: "ち",
            tsu: "つ",
            te: "て",
            to: "と",
            na: "な",
            ni: "に",
            nu: "ぬ",
            ne: "ね",
            no: "の",
            ha: "は",
            hi: "ひ",
            fu: "ふ",
            he: "へ",
            ho: "ほ",
            ma: "ま",
            mi: "み",
            mu: "む",
            me: "め",
            mo: "も",
            ya: "や",
            yu: "ゆ",
            yo: "よ",
            ra: "ら",
            ri: "り",
            ru: "る",
            re: "れ",
            ro: "ろ",
            wa: "わ",
            wo: "を",
            n: "ん",
          },
          {
            wi: "ゐ",
            we: "ゑ",
          },
          {
            ga: "が",
            gi: "ぎ",
            gu: "ぐ",
            ge: "げ",
            go: "ご",
            za: "ざ",
            ji: "じ",
            zu: "ず",
            ze: "ぜ",
            zo: "ぞ",
            da: "だ",
            ji2: "ぢ",
            zu2: "づ",
            de: "で",
            do: "ど",
            ba: "ば",
            bi: "び",
            bu: "ぶ",
            be: "べ",
            bo: "ぼ",
            pa: "ぱ",
            pi: "ぴ",
            pu: "ぷ",
            pe: "ぺ",
            po: "ぽ",
          },
          {
            xya: "ゃ",
            xyu: "ゅ",
            xyo: "ょ",
          },
        ),
        Reading: kanaRead({
          あ: "a",
          い: "i",
          う: "u",
          え: "e",
          お: "o",
          か: "ka",
          き: "ki",
          く: "ku",
          け: "ke",
          こ: "ko",
          さ: "sa",
          し: "shi",
          す: "su",
          せ: "se",
          そ: "so",
          た: "ta",
          ち: "chi",
          つ: "tsu",
          て: "te",
          と: "to",
          な: "na",
          に: "ni",
          ぬ: "nu",
          ね: "ne",
          の: "no",
          は: "ha",
          ひ: "hi",
          ふ: "fu",
          へ: "he",
          ほ: "ho",
          ま: "ma",
          み: "mi",
          む: "mu",
          め: "me",
          も: "mo",
          や: "ya",
          ゆ: "yu",
          よ: "yo",
          ら: "ra",
          り: "ri",
          る: "ru",
          れ: "re",
          ろ: "ro",
          わ: "wa",
          を: "wo",
          ん: "n",
          ゐ: "wi",
          ゑ: "we",
          が: "ga",
          ぎ: "gi",
          ぐ: "gu",
          げ: "ge",
          ご: "go",
          ざ: "za",
          じ: "ji",
          ず: "zu",
          ぜ: "ze",
          ぞ: "zo",
          だ: "da",
          ぢ: "ji",
          づ: "zu",
          で: "de",
          ど: "do",
          ば: "ba",
          び: "bi",
          ぶ: "bu",
          べ: "be",
          ぼ: "bo",
          ぱ: "pa",
          ぴ: "pi",
          ぷ: "pu",
          ぺ: "pe",
          ぽ: "po",
          きゃ: "kya",
          きゅ: "kyu",
          きょ: "kyo",
          ぎゃ: "gya",
          ぎゅ: "gyu",
          ぎょ: "gyo",
          しゃ: "sha",
          しゅ: "shu",
          しょ: "sho",
          じゃ: "ja",
          じゅ: "ju",
          じょ: "jo",
          ちゃ: "cha",
          ちゅ: "chu",
          ちょ: "cho",
          にゃ: "nya",
          にゅ: "nyu",
          にょ: "nyo",
          ひゃ: "hya",
          ひゅ: "hyu",
          ひょ: "hyo",
          びゃ: "bya",
          びゅ: "byu",
          びょ: "byo",
          ぴゃ: "pya",
          ぴゅ: "pyu",
          ぴょ: "pyo",
          みゃ: "mya",
          みゅ: "myu",
          みょ: "myo",
          りゃ: "rya",
          りゅ: "ryu",
          りょ: "ryo",
        }),
      },
      Katakana: {
        ...kanaTree(
          "Katakana",
          {
            a: "ア",
            i: "イ",
            u: "ウ",
            e: "エ",
            o: "オ",
            ka: "カ",
            ki: "キ",
            ku: "ク",
            ke: "ケ",
            ko: "コ",
            sa: "サ",
            shi: "シ",
            su: "ス",
            se: "セ",
            so: "ソ",
            ta: "タ",
            chi: "チ",
            tsu: "ツ",
            te: "テ",
            to: "ト",
            na: "ナ",
            ni: "ニ",
            nu: "ヌ",
            ne: "ネ",
            no: "ノ",
            ha: "ハ",
            hi: "ヒ",
            fu: "フ",
            he: "ヘ",
            ho: "ホ",
            ma: "マ",
            mi: "ミ",
            mu: "ム",
            me: "メ",
            mo: "モ",
            ya: "ヤ",
            yu: "ユ",
            yo: "ヨ",
            ra: "ラ",
            ri: "リ",
            ru: "ル",
            re: "レ",
            ro: "ロ",
            wa: "ワ",
            wo: "ヲ",
            n: "ン",
          },
          {
            wi: "ヰ",
            we: "ヱ",
          },
          {
            ga: "ガ",
            gi: "ギ",
            gu: "グ",
            ge: "げ",
            go: "ゴ",
            za: "ザ",
            ji: "ジ",
            zu: "ズ",
            ze: "ゼ",
            zo: "ゾ",
            da: "ダ",
            ji2: "ヂ",
            zu2: "ヅ",
            de: "デ",
            do: "ド",
            ba: "バ",
            bi: "ビ",
            bu: "ブ",
            be: "ベ",
            bo: "ボ",
            pa: "パ",
            pi: "ピ",
            pu: "プ",
            pe: "ペ",
            po: "ポ",
          },
          {
            xya: "ャ",
            xyu: "ュ",
            xyo: "ョ",
          },
        ),
        "More Combos": kanaList("Katakana", {
          va: "ヴァ",
          vi: "ヴィ",
          vu: "ヴ",
          ve: "ヴェ",
          vo: "ヴォ",
          fa: "ファ",
          fi: "フィ",
          fe: "フェ",
          fo: "フォ",
          wi: "ウィ",
          we: "ウェ",
          wo: "ウォ",
          tsa: "ツァ",
          tsi: "ツィ",
          tse: "ツェ",
          tso: "ツォ",
          twu: "トゥ",
          dwu: "ドゥ",
          thi: "ティ",
          dhi: "ディ",
        }),
        Reading: kanaRead({
          ア: "a",
          イ: "i",
          ウ: "u",
          エ: "e",
          オ: "o",
          カ: "ka",
          キ: "ki",
          ク: "ku",
          ケ: "ke",
          コ: "ko",
          サ: "sa",
          シ: "shi",
          ス: "su",
          セ: "se",
          ソ: "so",
          タ: "ta",
          チ: "chi",
          ツ: "tsu",
          テ: "te",
          ト: "to",
          ナ: "na",
          ニ: "ni",
          ヌ: "nu",
          ネ: "ne",
          ノ: "no",
          ハ: "ha",
          ヒ: "hi",
          フ: "fu",
          ヘ: "he",
          ホ: "ho",
          マ: "ma",
          ミ: "mi",
          ム: "mu",
          メ: "me",
          モ: "mo",
          ヤ: "ya",
          ユ: "yu",
          ヨ: "yo",
          ラ: "ra",
          リ: "ri",
          ル: "ru",
          レ: "re",
          ロ: "ro",
          ワ: "wa",
          ウォ: "wo",
          ン: "n",
          ウィ: "wi",
          ウェ: "we",
          ガ: "ga",
          ギ: "gi",
          グ: "gu",
          げ: "ge",
          ゴ: "go",
          ザ: "za",
          ジ: "ji",
          ズ: "zu",
          ゼ: "ze",
          ゾ: "zo",
          ダ: "da",
          ヂ: "ji",
          ヅ: "zu",
          デ: "de",
          ド: "do",
          バ: "ba",
          ビ: "bi",
          ブ: "bu",
          ベ: "be",
          ボ: "bo",
          パ: "pa",
          ピ: "pi",
          プ: "pu",
          ペ: "pe",
          ポ: "po",
          キャ: "kya",
          キュ: "kyu",
          キョ: "kyo",
          ギャ: "gya",
          ギュ: "gyu",
          ギョ: "gyo",
          シャ: "sha",
          シュ: "shu",
          ショ: "sho",
          ジャ: "ja",
          ジュ: "ju",
          ジョ: "jo",
          チャ: "cha",
          チュ: "chu",
          チョ: "cho",
          ニャ: "nya",
          ニュ: "nyu",
          ニョ: "nyo",
          ヒャ: "hya",
          ヒュ: "hyu",
          ヒョ: "hyo",
          ビャ: "bya",
          ビュ: "byu",
          ビョ: "byo",
          ピャ: "pya",
          ピュ: "pyu",
          ピョ: "pyo",
          ミャ: "mya",
          ミュ: "myu",
          ミョ: "myo",
          リャ: "rya",
          リュ: "ryu",
          リョ: "ryo",
          ヴァ: "va",
          ヴィ: "vi",
          ヴ: "vu",
          ヴェ: "ve",
          ヴォ: "vo",
          ファ: "fa",
          フィ: "fi",
          フェ: "fe",
          フォ: "fo",
          ツァ: "tsa",
          ツィ: "tsi",
          ツェ: "tse",
          ツォ: "tso",
          トゥ: "twu",
          ドゥ: "dwu",
          ティ: "thi",
          ディ: "dhi",
        }),
      },
    },
    Mathematics: {
      Squares: each(
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        (b) =>
          each(
            [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
            (y) => {
              const x = 10 * b + y
              return new DirectTreeCard(
                x + "²",
                x + "²",
                x * x + "",
                ["Mathematics", "Squares"],
                1 / 20,
              )
            },
            (y) => 10 * b + y + "",
          ),
        (b) => `${10 * b + 1}~${10 * b + 10}`,
      ),
    },
  },
  (value): value is Leaf =>
    value instanceof DirectTreeCard || value instanceof Generator,
)
