export const RISOLI = "/viossa72.pdf"

export function sortWords(a: string, b: string) {
  const ax =
    a.startsWith("-") ? 0
    : a.endsWith("-") ? 1
    : 2
  const bx =
    b.startsWith("-") ? 0
    : b.endsWith("-") ? 1
    : 2

  if (ax - bx != 0) {
    return ax - bx
  }

  return a > b ? 1 : -1
}

export function sortPairs(
  [a]: readonly [string, ...unknown[]],
  [b]: readonly [string, ...unknown[]],
) {
  return sortWords(a, b)
}

export type Content =
  | string // shorthand for no exposed words
  | [taught: string, exposed: string]

export type Fal =
  | "tingko"
  | "suruko"
  | "lihko"
  | "troko"
  | "pashko"
  | "medko"
  | "sporko"
  | "kotobanen"
  | "namae"
  | "hofliko"
  | "atai"
  | "etuniko"
  | "kokoroko"

export type Falnen =
  | "varge"
  | "fami"
  | "fraut"
  | "hanutro"
  | "lasku"
  | "ovashi"
  | "pashko"
  | "plasnamae"
  | "raz" // lyk ima, ende
  | "tyd" // lyk sho, mwuai
  | "vonating"
  | "kokoro"
  | "toshitel"
  | "strela"
  | "namting"
  | "glugting"
  | "kun"
  | "kokoro na aistia"
  | "(sjiranai)"

export interface RawWordData {
  readonly anki: true
  readonly emoji: string
  readonly fal: Fal | readonly [Fal, ...Fal[]]
  readonly falnen: Falnen | readonly [Falnen, ...Falnen[]]
  readonly imi?: string | undefined
  readonly lyk?: readonly string[] | undefined
  readonly kakutro?: readonly string[] | undefined
  readonly kundr?: readonly string[] | undefined
  readonly tatoeba?: readonly string[] | undefined
}

export interface WordData extends RawWordData {
  readonly eins: boolean
}

// #region riso
export const riso: Record<number, Content> = {
  11: "jaa",
  12: ["akk nai fshto ka bluma", "eins kotoba -ara danke nil ie"],
  13: ["un du sore vi dok hej", "pashun kotoba"],
  14: "pashun -djin opeta lera tajka ojogi",
  15: "glossa -ossa angl- nihon- espanj-",
  16: "kundr",
  17: "sama lik tsigau",
  18: "kirain silba kotoba fras punkt",
  19: "nil joku al ru midore",
  20: ["per ringo torta cola bra warui cafe", "kotoba du al pashun"],
  21: "afto tuo asoko ringo huin pashun bluma lera -djin pinue",
  22: "ie fugel baum maredur",
  23: ["namai fu huin", "jaa ie ka du un"],
  24: ["ru ciro midore au lezi glug cafe", "ie pashun lera nam sore du lik"],
  25: ["awen slucha bra warui glau trict", "un du au nai ka"],
  26: ["vil nam mis", "afto mama oy pashun"],
  27: ["da pinuno hanu oy", "os vil afto nai"],
  28: [
    "bite danke nil gomen cer ringo banan",
    "ka da pinuno nai hanu vil anta na un bra",
  ],
  29: "jalaka hanu kaku siru cola valtsa tasti ergo suru kotoba",
  30: ["os gelt aschor", "vil nam glug du un mange"],
  31: [
    "ein ni tre kiere go eksi nana kase non den apar mange lasku",
    "os tsisai sama au ie",
  ],
  32: ["mit kuchi se me hir corva njui hana", "du nam"],
  33: "tropos per nam sjkoi siru maha",
  34: ["deki", "un nam jalaka hanu nai"],
  35: ["ting hjerne torta cer tualet gavat riso katana plas", "kotoba nam"],
  36: ["men har vil", "ringo banan nai un nam sore ting"],
  37: "tyd dan ima mirai",
  38: [
    "gammel ryodjin mama papa fi kzin sawi bruur sisco un matetun matetundjin pojk tutr lapsi mipi nia fami",
    "un",
  ],
  39: [
    "roza ru portocale ciro midore sini blau murasace shiro gris curo cafe",
    "al kotoba afto varge tsigau nai sama",
  ],
  40: "tsisai stuur",
  41: "simpel haaste",
  42: ["na", "un hanu du maha riso afto ergo plas hej vikoli"],
  43: ["daag uuk mwuai tosui", "kotoba per tyd stuur"],
  44: ["sho funn dzikjaan daag", "kotoba per tyd tsisai"],
  45: "prapataj akote paara praapa",
  46: "tsatain tun",
  47: ["vona sjinu uten", "kundr mit"],
  48: "strela nord west ost sud oba ljeva hina unna migi fura",
  49: ["klar tun", "kundr"],
  50: ["mietta k'", "pashun huin portocale ie al"],
  51: [
    "li sit iske",
    "au du nai glug iske sjinu vil lera viossa da hanu angl-",
  ],
  52: ["jam gaja sot magasin", "pashun na ringo nai banan nil ting mange"],
  53: ["grun naze cola jalaka", "ka afto pashun nai mange sore deki"],
  54: ["kara made rzinzai huomi", "pashun jalaka"],
  55: ["tsui", "sore hanu ringo"],
  56: ["plus minus gammel glau vapa bjurki ka", "stuur"],
  57: ["kjomi", "sore vil siru plus tsui afto os"],
  58: ["inje ecso kot huin baksu huomi", "kundr"],
  59: ["ein den hjaku tuhat lacsaq catie ip- kn-", "lasku ni tre kiere go"],
  60: ["hadji owari bli- po-", "un nai nam kundr glau"],
  61: ["benj jamete", "un jalaka nai lik sama kundr"],
  62: ["uwaki", "ka na viossa nai deki hanu afto grun angl- kotoba ie espanj-"],
  63: "heljo vulcanis aifroidis gaja airis jainos crenos mirairis posaidis",
  64: ["plasdai sol gaja avara luna -dai samui vapa lantdai", "kundr stuur"],
  65: ["-yena libre na circas kaku", "pashun kini sore"],
  66: ["-yena auki kini kot dvera na", "kundr"],
  67: "auki kini",
  68: [
    "fraut ringo crusca portocale lemo banan bestfraut uva vinjafraut cerfraut ahavja nihunfraut persefraut mago ananas niog afefraut fugelfraut",
    "al afto du deki nam",
  ],
  69: ["fal -ki", "jam ni fu pashun dare ka viossa au nai"],
  70: [
    "spor svar",
    "du vil os nai nam ting sot ie bra os warui na du ka tyd ima un mange -s mwuai daag",
  ],
  71: [
    "spor dare doko cosce naze perka hur katai atai",
    "dare vinjafraut fraut har un jam ringo tre sjkoi du jainos kara bruk",
  ],
  72: ["fugel maredur atechi protofugel bihmidur njudur dur bagge", "al"],
}

export interface Word extends WordData {
  readonly kotoba: string
  readonly opetaNa: readonly number[]
  readonly hanuNa: readonly number[]
}

export interface MutableWord {
  kotoba: string
  opetaNa: number[]
  hanuNa: number[]
}

export interface Slide {
  readonly index: number
  readonly opetako: readonly string[]
  readonly hanuko: readonly string[]
}

export interface MutableSlide {
  index: number
  opetako: string[]
  hanuko: string[]
}

export function makeWordList(): ReadonlyMap<string, Word> {
  const map = new Map<string, MutableWord>()

  for (const [index, slide] of Object.entries(riso)) {
    const taught =
      typeof slide == "string" ? slide.split(" ") : slide[0].split(" ")

    const referenced = typeof slide == "string" ? [] : slide[1].split(" ")

    for (const word of taught) {
      const existing = map.get(word) || {
        kotoba: word,
        opetaNa: [],
        hanuNa: [],
      }

      if (!existing.opetaNa.includes(+index)) {
        existing.opetaNa.push(+index)
      }

      map.set(word, existing)
    }

    for (const word of referenced) {
      const existing = map.get(word) || {
        kotoba: word,
        opetaNa: [],
        hanuNa: [],
      }

      if (!existing.hanuNa.includes(+index)) {
        existing.hanuNa.push(+index)
      }

      map.set(word, existing)
    }
  }

  for (const [key, value] of Object.entries(kotobasirupravda)) {
    let mapval = map.get(key)

    if (!mapval) {
      mapval = { hanuNa: [], opetaNa: [], kotoba: key }
      map.set(key, mapval)
    }

    Object.assign(mapval, value)
  }

  let missing: string[] = []
  for (const key of map.keys()) {
    if (!(key in kotobasirupravda)) {
      missing.push(key)
    }
  }
  if (missing.length) {
    throw new Error("Missing words " + missing.join(", ") + " from database.")
  }

  return new Map(
    Array.from(map as any as Map<string, Word>).sort(([a], [b]) => {
      const ax =
        a.startsWith("-") ? 0
        : a.endsWith("-") ? 1
        : 2
      const bx =
        b.startsWith("-") ? 0
        : b.endsWith("-") ? 1
        : 2

      if (ax - bx != 0) {
        return ax - bx
      }

      return a > b ? 1 : -1
    }),
  )
}

export function makeSlideList(): ReadonlyMap<number, Slide> {
  const map = new Map<number, MutableSlide>()

  for (const [index, slide] of Object.entries(riso)) {
    const opetako =
      typeof slide == "string" ? slide.split(" ") : slide[0].split(" ")

    const hanuko = typeof slide == "string" ? [] : slide[1].split(" ")

    map.set(+index, {
      index: +index,
      hanuko,
      opetako,
    })
  }

  return map
}

const kotobasirumahena: Record<string, RawWordData> = {
  "100": {
    anki: true,
    emoji: "🤣😂😆",
    fal: "kokoroko",
    falnen: "(sjiranai)",
  },
  "angl-": {
    anki: true,
    emoji: "🇬🇧🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    fal: "namae",
    falnen: "plasnamae",
    imi: "fu anglant os anglossa",
  },
  "doich-": {
    anki: true,
    emoji: "🇩🇪",
    fal: "namae",
    falnen: "plasnamae",
    imi: "fu doichlant os doichossa",
  },
  "espanj-": {
    anki: true,
    emoji: "🇪🇸",
    fal: "namae",
    falnen: "plasnamae",
    imi: "fu espanjalant os espanjossa",
  },
  "ip-": {
    anki: true,
    emoji: "",
    fal: "kotobanen",
    falnen: "lasku",
    tatoeba: [
      "ipni sama 1,000,000 sama milyon.",
      "iptre sama 1,000,000,000.",
      "ipkiere sama 1,000,000,000,000.",
    ],
  },
  "kn-": {
    anki: true,
    emoji: "–",
    fal: "kotobanen",
    falnen: "lasku",
    imi: "nil uten lasku",
    tatoeba: [
      "kntre sama nil uten tre.",
      "kn-lasku sama nil uten lasku afto. ",
    ],
  },
  "nihon-": {
    anki: true,
    emoji: "🇯🇵",
    fal: "namae",
    falnen: "plasnamae",
    imi: "fu nihonlant os nihonossa",
  },
  "-a": {
    anki: true,
    emoji: "2️⃣",
    fal: "kotobanen",
    falnen: "lasku",
    imi: "jam ni fu afto",
    lyk: ["ni"],
    tatoeba: ["un har ein huin. un har ni huina. un har tre huinara."],
  },
  "-ara": {
    anki: true,
    emoji: "🔢",
    fal: "kotobanen",
    falnen: "lasku",
    imi: "jam plusni fu afto",
    tatoeba: ["un har ein huin. un har ni huina. un har tre huinara."],
  },
  "-dai": {
    anki: true,
    emoji: "",
    fal: "kotobanen",
    falnen: "(sjiranai)",
    imi: "afto ie plustuur de altyd.",
    tatoeba: [
      "amerikalant ie lant. noramerikalantdai ie lantdai (sore har lant mange inje sore).",
    ],
  },
  "-s": {
    anki: true,
    emoji: "🥇🥈🥉",
    fal: "kotobanen",
    falnen: "lasku",
    tatoeba: [
      "un nam sotting. un nammirai ovashi. eins, un nam sotting. nis, un nam ovashi.",
      "un au du rzinsaj. un rzinsaj mit tsisai tyd. du rzinsaj mit stuur tyd. un owari eins, au du owari nis.",
    ],
  },
  "-tsa": {
    anki: true,
    emoji: "",
    fal: "kotobanen",
    falnen: "(sjiranai)",
    imi: "un vil ke du ...",
    lyk: ["da"],
    tatoeba: ["namtsa = 'un vil ke du nam'"],
  },
  "-yena": {
    anki: true,
    emoji: "",
    fal: "kotobanen",
    falnen: "hanutro",
    tatoeba: [
      "kot auki circas. circas aukiyena na kot.",
      "un kaku libre. libre kakuyena (na un).",
    ],
  },
  afto: {
    anki: true,
    emoji: "",
    fal: "atai",
    falnen: "(sjiranai)",
    lyk: ["asoko", "tuo"],
  },
  ahavja: {
    anki: true,
    emoji: "🫐",
    fal: "tingko",
    falnen: "fraut",
  },
  aifroidis: {
    anki: true,
    emoji: "",
    fal: "namae",
    falnen: "plasnamae",
    imi: "heljo nis na pandos fun",
  },
  airis: {
    anki: true,
    emoji: "",
    fal: "namae",
    falnen: "plasnamae",
    imi: "heljo kieres na pandos fun",
  },
  aistia: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
    lyk: ["cocro"],
    tatoeba: [
      "aistia\n\nsmak [mihht glossa 👅]\nse [mihht me 👁️]\nryr [mihht haant ✋]\nhoer [mihht korva 👂]\nnioi [mihht hana 👃]",
    ],
  },
  aja: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
    lyk: ["sjkoi"],
    tatoeba: ["du aja auto"],
  },
  akk: {
    anki: true,
    emoji: "",
    fal: "hofliko",
    falnen: "(sjiranai)",
    kundr: ["nai"],
  },
  akote: {
    anki: true,
    emoji: "",
    fal: "medko",
    falnen: "(sjiranai)",
    imi: "prapataj tsisai",
    kundr: ["praapa"],
    lyk: ["paara"],
    tatoeba: [
      "nuyorkplas na akote fu newarkplas, men sore na praapa fu nihonlant",
    ],
  },
  al: {
    anki: true,
    emoji: "",
    fal: "atai",
    falnen: "lasku",
    kundr: ["nil"],
    lyk: ["joku", "joki"],
    tatoeba: ["al ringo ru: 🍎🍎🍎🍎🍎. nai al ringo ru: 🍎🍎🍎🍏🍎."],
  },
  ananas: {
    anki: true,
    emoji: "🍍",
    fal: "tingko",
    falnen: "fraut",
  },
  ander: {
    anki: true,
    emoji: "",
    fal: "atai",
    falnen: "(sjiranai)",
    tatoeba: [
      "A har ringo au banan.\nB: da anta fraut na un.\nA anta ringo.\nB: nai ringo, da anta ander fraut.\nA anta banan.",
    ],
  },
  anta: {
    anki: true,
    emoji: "🫴",
    fal: "suruko",
    falnen: "(sjiranai)",
    tatoeba: ["un har ringo. un anta ringo na du. ima, du har ringo."],
  },
  apar: {
    anki: true,
    emoji: "",
    fal: "atai",
    falnen: "lasku",
    imi: "atai fu afto ting ie tsisai.",
    kundr: ["mange"],
    tatoeba: [
      "un har apar ringo: 🍎🍎🍎. du har mange ringo: 🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎.",
    ],
  },
  apu: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
    tatoeba: [
      "🧑‍🎓: ka 'atai'?\n🧑: nai siru. oy gammeldjin, da apu!\n🧑‍🏫: 'atai' lyk 'lasku'. inje 🍎🍎, atai fu ringo ie ni. ringo nai har lasku.\nopetadjin apu mellandjin na opeta.",
    ],
  },
  aschor: {
    anki: true,
    emoji: "🤑🏦💸",
    fal: "lihko",
    falnen: "(sjiranai)",
    imi: "aschordjin har mange gelt.",
    lyk: ["gelt"],
  },
  asoko: {
    anki: true,
    emoji: "",
    fal: "atai",
    falnen: "(sjiranai)",
    imi: "asoko ting ie na prapa fu un",
    lyk: ["afto", "tuo"],
  },
  atai: {
    anki: true,
    emoji: "🔢",
    fal: "tingko",
    falnen: "lasku",
    lyk: ["lasku"],
    tatoeba: [
      "atai fu ringo inje 🍎🍎 ie ni",
      "atai fu ringo inje 🍎🍎🍎🍎 ie kiere",
    ],
  },
  atechi: {
    anki: true,
    emoji: "🦎🐍",
    fal: "tingko",
    falnen: "vonating",
    kakutro: ["riobohna"],
  },
  au: {
    anki: true,
    emoji: "➕",
    fal: "etuniko",
    falnen: "(sjiranai)",
    imi: "'X au Y suru' imi 'X suru. Y suru sama.'",
    tatoeba: ["un har ringo au banan. un: 💁🍎🍌"],
  },
  auauau: {
    anki: true,
    emoji: "➕...",
    fal: "troko",
    falnen: "(sjiranai)",
    imi: "'X au Y au Z auauau' imi 'X au Y au Z au ting sama'",
    kakutro: ["auau"],
    tatoeba: ["kotoba fraut imi ringo au banan au ananas au cerfraut auau"],
  },
  auki: {
    anki: true,
    emoji: "🔓📖📭📂",
    fal: "suruko",
    falnen: "(sjiranai)",
    kundr: ["kini"],
    tatoeba: ["🔓📖📭📂 ie auki. 🔒📘📪📁 ie kini."],
  },
  auto: {
    anki: true,
    emoji: "🚗🚓🚘🚖",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  avara: {
    anki: true,
    emoji: "🌌",
    fal: "tingko",
    falnen: "plasnamae",
    imi: "mangenilting",
    tatoeba: [
      "inje pandos, jam solh au heljara au avara mange.",
      "avara plas stuur. mange tsisai ting ie inje sore.",
    ],
  },
  awen: {
    anki: true,
    emoji: "",
    fal: "troko",
    falnen: "(sjiranai)",
    tatoeba: ["A: ka slucha?\nB: un bra? au na du?\nA: un bra auen!"],
  },
  azyci: {
    anki: true,
    emoji: "🫘",
    fal: "tingko",
    falnen: "ovashi",
  },
  bagge: {
    anki: true,
    emoji: "🐛🐜🐝🪲",
    fal: "tingko",
    falnen: "vonating",
  },
  baksu: {
    anki: true,
    emoji: "📦🎁🗳️🥡",
    fal: "tingko",
    falnen: "vonating",
    lyk: ["mulbaksu"],
  },
  bamba: {
    anki: true,
    emoji: "💣",
    fal: "tingko",
    falnen: "vonating",
  },
  banan: {
    anki: true,
    emoji: "🍌",
    fal: "tingko",
    falnen: "vonating",
  },
  baum: {
    anki: true,
    emoji: "🌴🌳🌲🎄",
    fal: "tingko",
    falnen: "vonating",
  },
  benj: {
    anki: true,
    emoji: "",
    fal: "troko",
    falnen: "raz",
    kundr: ["jamete"],
    tatoeba: [
      "un nam. li un benj nam, sit un nam. li un jamete nam, sit un nai nam.",
    ],
  },
  berk: {
    anki: true,
    emoji: "🗻⛰️🏔️",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  bestfraut: {
    anki: true,
    emoji: "🍉🍈",
    fal: "tingko",
    falnen: "fraut",
  },
  bihmidur: {
    anki: true,
    emoji: "🦄🐲",
    fal: "tingko",
    falnen: "vonating",
    imi: "dur ka na gvir",
  },
  bistra: {
    anki: true,
    emoji: "🐌🚋🐢",
    fal: "lihko",
    falnen: "(sjiranai)",
    imi: "bruk tyd stuur",
    kundr: ["hiras"],
  },
  bite: {
    anki: true,
    emoji: "🥺🙏",
    fal: "hofliko",
    falnen: "(sjiranai)",
    imi: "brukena grun du vil hofli",
    tatoeba: [
      "A: bite, da pinuno!\nB: du hofli mange 😊! un pinuno 🤫.",
      "A: da pinuno!\nB: du nai hofli 😠! un benj hanu 🗣️.",
    ],
  },
  bjelu: {
    anki: true,
    emoji: "🔔🛎️",
    fal: "tingko",
    falnen: "(sjiranai)",
    kakutro: ["timba"],
  },
  bjurki: {
    anki: true,
    emoji: "🤮🤒🤧🤢",
    fal: "lihko",
    falnen: "(sjiranai)",
    imi: "vona waryj",
  },
  bjurkiplas: {
    anki: true,
    emoji: "🏥",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "plas ka bjurkidjin sjkoi kara grun sore vil bli naibjurki",
  },
  blau: {
    anki: true,
    emoji: "💙🔵🟦🔷",
    fal: "lihko",
    falnen: "varge",
  },
  bli: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "raz",
    tatoeba: ["👶 bli 👵", "🐛 bli 🦋"],
  },
  blin: {
    anki: true,
    emoji: "🤬",
    fal: "kokoroko",
    falnen: "(sjiranai)",
    tatoeba: ["A sjkoi 🧱 kara.\nA: blin!\nA: jalak f'un waruiii!"],
  },
  bluma: {
    anki: true,
    emoji: "🪷🌷🌺💐🌻🪻🌸🌹",
    fal: "tingko",
    falnen: "vonating",
  },
  boozy: {
    anki: true,
    emoji: "😡😠",
    fal: "lihko",
    falnen: "kokoro",
    tatoeba: [
      "A ergo mange na sjkola. A nai vil ergo.\nA: un cocro boozy! un nai vil ergo! al ie warui na un! 😡! un vil 👊 alting!",
    ],
  },
  bra: {
    anki: true,
    emoji: "👍",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["warui"],
    tatoeba: ["A: ka slucha na du?\nB: un bra 👍! au na du?\nA: un warui 👎."],
  },
  breska: {
    anki: true,
    emoji: "🐢",
    fal: "tingko",
    falnen: "vonating",
  },
  bruk: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "suruko per mit. li du bruk ting, du (suruko) mit sore.",
    lyk: ["mit"],
  },
  bruur: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "fami",
    imi: "mjes ka mahena na ryodjin sama",
    tatoeba: [
      "un har ein bruur. namae fsore ie sajli. ryodjin f'sajli sama ryodjin fun.",
    ],
  },
  cafe: {
    anki: true,
    emoji: "☕🤎🟤🟫",
    fal: ["tingko", "lihko"],
    falnen: "(sjiranai)",
  },
  catie: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "lasku",
    imi: "100,000",
  },
  cer: {
    anki: true,
    emoji: "🫀",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "ting ka mange dur har inje sore au ka mahasjkoi 🩸",
  },
  cerfraut: {
    anki: true,
    emoji: "🍓",
    fal: "tingko",
    falnen: "fraut",
  },
  circas: {
    anki: true,
    emoji: "💡🔦🔆🏮",
    fal: "tingko",
    falnen: "(sjiranai)",
    kundr: ["kury"],
  },
  ciro: {
    anki: true,
    emoji: "💛🟡🟨",
    fal: "lihko",
    falnen: "varge",
  },
  cocro: {
    anki: true,
    emoji: "",
    fal: ["tingko", "suruko"],
    falnen: "(sjiranai)",
    kakutro: ["kokoro"],
    lyk: ["aistia"],
  },
  cola: {
    anki: true,
    emoji: "😴💤🛌",
    fal: "suruko",
    falnen: "(sjiranai)",
    tatoeba: ["al pershunn mus cola, os sore sjinu"],
  },
  corva: {
    anki: true,
    emoji: "👂",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  cosce: {
    anki: true,
    emoji: "",
    fal: "sporko",
    falnen: "(sjiranai)",
    imi: "ka tyd",
  },
  crenos: {
    anki: true,
    emoji: "🪐",
    fal: "tingko",
    falnen: "plasnamae",
    imi: "heljo eksis na pandos fun",
  },
  cris: {
    anki: true,
    emoji: "🦁🦈⚠️",
    fal: "lihko",
    falnen: "(sjiranai)",
    imi: "afto deki shinu du",
    kundr: ["siha"],
    tatoeba: ["🐯 cris. 🐱 siha."],
  },
  crusca: {
    anki: true,
    emoji: "🍐",
    fal: "tingko",
    falnen: "fraut",
  },
  cunin: {
    anki: true,
    emoji: "👑🫅",
    fal: "lihko",
    falnen: "(sjiranai)",
  },
  curo: {
    anki: true,
    emoji: "⚫🖤⬛",
    fal: "lihko",
    falnen: "varge",
    kundr: ["shiro"],
  },
  da: {
    anki: true,
    emoji: "",
    fal: "kokoroko",
    falnen: "(sjiranai)",
    imi: "'da X' imi 'oy du, un vil ka du X. du mus X.'",
    lyk: ["-tsa"],
    tatoeba: ["A hanu mange.\nB: oy A, da pinuno!\nA pinuno 🤐."],
  },
  daag: {
    anki: true,
    emoji: "🌞→🌓→🌞",
    fal: "tingko",
    falnen: "tyd",
    tatoeba: ["inje daag ein, solh sjkoi un kara, un made, un kara gen"],
  },
  dan: {
    anki: true,
    emoji: "⬅️🕰️",
    fal: "troko",
    falnen: "raz",
    imi: "tyd ka nai ieima na her",
    kundr: ["mirai"],
    lyk: ["ima"],
    tatoeba: ["A nam.\nA nai nam.\nA dan nam."],
  },
  danke: {
    anki: true,
    emoji: "🙏😁",
    fal: "hofliko",
    falnen: "(sjiranai)",
    tatoeba: [
      "li pashun apu du, da hanu 'danki'",
      "A: ka 'bluma'?\nB: bluma = 🌹.\nA: danki!\nB: nil wil!",
    ],
  },
  dare: {
    anki: true,
    emoji: "",
    fal: "sporko",
    falnen: "(sjiranai)",
    imi: "ka pashun",
  },
  darem: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  daremdjin: {
    anki: true,
    emoji: "👮👮‍♂️👮‍♀️",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  de: {
    anki: true,
    emoji: "🕰️",
    fal: "medko",
    falnen: "tyd",
    kundr: ["ze"],
    tatoeba: ["un nam de glug. eins (ima), un nam. nis, un glug."],
  },
  davai: {
    anki: true,
    emoji: "🥳🎉🎊",
    fal: "kokoroko",
    falnen: "(sjiranai)",
    tatoeba: ["li du kokore glaumange, sit du vil hanu 'davai'"],
  },
  der: {
    anki: true,
    emoji: "📍👉",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "tuo plas",
    lyk: ["hapigo", "her"],
  },
  deki: {
    anki: true,
    emoji: "",
    fal: "troko",
    falnen: "(sjiranai)",
    kakutro: ["-ki"],
    tatoeba: ["du deki nam 🍎", "du nai deki nam 🚗"],
  },
  den: {
    anki: true,
    emoji: "🔟",
    fal: "tingko",
    falnen: "lasku",
    imi: "10",
  },
  denwa: {
    anki: true,
    emoji: "📱",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "~ kompjunen",
    lyk: ["kompju"],
  },
  diarper: {
    anki: true,
    emoji: "🐍",
    fal: "tingko",
    falnen: "vonating",
  },
  diskord: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "plasnamae",
  },
  dok: {
    anki: true,
    emoji: "🫵",
    fal: "pashko",
    falnen: "pashko",
    imi: "du mange",
    lyk: ["du"],
  },
  doko: {
    anki: true,
    emoji: "📍?",
    fal: "sporko",
    falnen: "(sjiranai)",
    imi: "ka plas",
  },
  dronet: {
    anki: true,
    emoji: "👸",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "cunin onna",
  },
  du: {
    anki: true,
    emoji: "🫵",
    fal: "pashko",
    falnen: "pashko",
    lyk: ["dok"],
  },
  dua: {
    anki: true,
    emoji: "😍🥰🫶",
    fal: "suruko",
    falnen: "kokoro",
    kundr: ["viha"],
  },
  dur: {
    anki: true,
    emoji: "🦝🐶🦎🐟🪼🦈🐺🦀",
    fal: "tingko",
    falnen: "vonating",
  },
  dush: {
    anki: true,
    emoji: "🛀🚿",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  dvera: {
    anki: true,
    emoji: "🚪",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  dzikjaan: {
    anki: true,
    emoji: "🕐🕑🕒🕓🕔",
    fal: "tingko",
    falnen: "tyd",
    tatoeba: ["jam 24 dzikjann na ein dag"],
  },
  ecso: {
    anki: true,
    emoji: "📤",
    fal: "medko",
    falnen: "(sjiranai)",
    kundr: ["inje"],
  },
  efles: {
    anki: true,
    emoji: "👃👍",
    fal: "lihko",
    falnen: "kokoro na aistia",
    imi: "braa na njui",
    kundr: ["froreenj"],
  },
  ein: {
    anki: true,
    emoji: "1️⃣",
    fal: "atai",
    falnen: "lasku",
    imi: "1",
  },
  eins: {
    anki: true,
    emoji: "🥇",
    fal: "lihko",
    falnen: "lasku",
    imi: "ein + -s",
  },
  eksi: {
    anki: true,
    emoji: "6️⃣",
    fal: "atai",
    falnen: "lasku",
    imi: "6",
  },
  ende: {
    anki: true,
    emoji: "",
    fal: "troko",
    falnen: "raz",
    imi: "dan au ima",
  },
  enterrena: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "inje + ter + -yena",
  },
  ergo: {
    anki: true,
    emoji: "👷🧑‍🏫🧑‍💼",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  fal: {
    anki: true,
    emoji: "🟨🔴🔷",
    fal: "tingko",
    falnen: "(sjiranai)",
    tatoeba: ["yam ni fal fu pershun: dare ka hanuki viossa, a dare ka nai"],
  },
  fami: {
    anki: true,
    emoji: "👪👨‍👨‍👧‍👧👨‍👩‍👦‍👦👨‍👨‍👧‍👦",
    fal: "tingko",
    falnen: "fami",
  },
  farza: {
    anki: true,
    emoji: "🌡️📏⚖️📐",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "ting per sjiru ka vecht os pitka osos",
  },
  fearie: {
    anki: true,
    emoji: "🌈",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  festako: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "hanutro",
    imi: "kotobanen ka akote na ranjako",
    tatoeba: [
      "inje kotoba 'amerikalant', -lant ie festako",
      "inje kotoba 'tres', -s ie festako.",
    ],
  },
  fi: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "fami",
    imi: "mipi fu ryodjin os matetundjin fsore",
  },
  film: {
    anki: true,
    emoji: "🎞️",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "ting ke 📹 ufne",
  },
  flacha: {
    anki: true,
    emoji: "🏁🏳️‍🌈🏳️🚩",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  fras: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "~ kotoba mange",
    lyk: ["kotoba", "punkt"],
  },
  fraut: {
    anki: true,
    emoji: "🍎🍓🥝🍑🍒🍋🍌🥭",
    fal: "tingko",
    falnen: "fraut",
  },
  froreenj: {
    anki: true,
    emoji: "👃👎",
    fal: "lihko",
    falnen: "kokoro na aistia",
    imi: "warui na njyi",
    kundr: ["efles"],
  },
  fshto: {
    anki: true,
    emoji: "📥🧠👍",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "'un siru braa'",
    lyk: ["siru"],
  },
  fu: {
    anki: true,
    emoji: "",
    fal: "medko",
    falnen: "(sjiranai)",
  },
  fuga: {
    anki: true,
    emoji: "🃏🪪💳",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "librenen ka opeta sirunen",
    tatoeba: ["vi spil mit fuga"],
  },
  fugel: {
    anki: true,
    emoji: "🐧🦉🦅🐥🦜🐦🦆🐔",
    fal: "tingko",
    falnen: "vonating",
  },
  fugelfraut: {
    anki: true,
    emoji: "🥝",
    fal: "tingko",
    falnen: "fraut",
    kakutro: ["afefraut"],
  },
  funn: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "tyd",
    tatoeba: ["jam 60 funn na ein dzikjann", "jan 1440 funn na ein daag"],
  },
  fura: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "strela",
    kundr: ["hina"],
  },
  gaja: {
    anki: true,
    emoji: "🌏🌍🌎",
    fal: "tingko",
    falnen: "plasnamae",
    imi: "heljo ke un au du vona na",
  },
  gammel: {
    anki: true,
    emoji: "🧓👵👴",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["neo"],
  },
  gavat: {
    anki: true,
    emoji: "🎁",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  gelt: {
    anki: true,
    emoji: "💰💵🪙",
    fal: "tingko",
    falnen: "(sjiranai)",
    lyk: ["aschor"],
  },
  gen: {
    anki: true,
    emoji: "🕰️+1",
    fal: "troko",
    falnen: "raz",
    imi: "ein plus raz",
    tatoeba: ["A: oy B, da hanu!\nB hanu.\nA: da hanu gen!\nB hanu gen."],
  },
  glas: {
    anki: true,
    emoji: "😎🕶️",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  glau: {
    anki: true,
    emoji: "😁😄😃😀",
    fal: "lihko",
    falnen: "kokoro",
  },
  glaubi: {
    anki: true,
    emoji: "½",
    fal: "troko",
    falnen: "(sjiranai)",
    imi: "mellan akk au nai",
    tatoeba: ["100 = akk\n50 = glaubi\n0 = nai"],
  },
  glossa: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "ting ke al pershun hanu mit",
    kakutro: ["-ossa"],
    lyk: ["smak"],
  },
  glug: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "nam iske os cafe osos",
    lyk: ["nam"],
  },
  go: {
    anki: true,
    emoji: "5️⃣",
    fal: "atai",
    falnen: "lasku",
  },
  godja: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "ka akote na ecso fu ting",
    lyk: ["piel"],
    tatoeba: [
      "aldjin har godja",
      "godja fu pashun ie lacte stuur vonatro na sore",
      "li du vil nam portocale 🍊, sit du mus mahanaigvir godja fsore",
    ],
  },
  gomen: {
    anki: true,
    emoji: "😔🙏🙇",
    fal: "kokoroko",
    falnen: "(sjiranai)",
  },
  gris: {
    anki: true,
    emoji: "🩶",
    fal: "lihko",
    falnen: "varge",
  },
  grun: {
    anki: true,
    emoji: "",
    fal: "medko",
    falnen: "(sjiranai)",
    lyk: ["naze", "per"],
  },
  gus: {
    anki: true,
    emoji: "👍➡️🧑",
    fal: "suruko",
    falnen: "(sjiranai)",
    tatoeba: ["li du gus ting, ting bra na du."],
  },
  gvir: {
    anki: true,
    emoji: "🐴🌲✅",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "ein os plusein afto ie na velt. ~ jam afto.",
    tatoeba: ["🐴 gvir. 🦄 nai gvir."],
  },
  haaste: {
    anki: true,
    emoji: "",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["simpel"],
  },
  hadji: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "raz",
    kakutro: ["bli-"],
  },
  haesa: {
    anki: true,
    emoji: "🗣️📛",
    fal: "suruko",
    falnen: "(sjiranai)",
    tatoeba: ['A haesa B "C". namae fu B "C" na A'],
  },
  hana: {
    anki: true,
    emoji: "👃",
    fal: "tingko",
    falnen: "(sjiranai)",
    lyk: ["njui"],
  },
  hanj: {
    anki: true,
    emoji: "½",
    fal: "tingko",
    falnen: "lasku",
    imi: "mellan tsatain na al au nil",
  },
  hant: {
    anki: true,
    emoji: "🖐️✋",
    fal: "tingko",
    falnen: "(sjiranai)",
    lyk: ["ryr"],
  },
  hanu: {
    anki: true,
    emoji: "🗣️",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  hapigo: {
    anki: true,
    emoji: "📍👉",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "asoko plas",
    lyk: ["her", "der"],
  },
  har: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  hej: {
    anki: true,
    emoji: "",
    fal: "pashko",
    falnen: "pashko",
    imi: "sore mange",
    lyk: ["sore"],
  },
  hel: {
    anki: true,
    emoji: "",
    fal: "lihko",
    falnen: "(sjiranai)",
    imi: "al fu afto ting",
    kundr: ["tel"],
    tatoeba: ["🎂 hel torta. 🍰 tel torta."],
  },
  helena: {
    anki: false,
    emoji: "👀🦋😍",
    fal: "lihko",
    falnen: "kokoro na aistia",
    imi: "bra na se",
    kundr: ["nitshizta"],
  },
  helenakaku: {
    anki: true,
    emoji: "𝓀𝒶𝓀𝓊",
    fal: "suruko",
    falnen: "(sjiranai)",
    tatoeba: ["𝒶𝒻𝓉ℴ 𝒽ℯ𝓁ℯ𝓃𝒶𝓀𝒶𝓀𝓊. afto nai helenakaku."],
  },
  heljo: {
    anki: true,
    emoji: "🪐🌎",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "plasdaidai",
  },
  henci: {
    anki: true,
    emoji: "💭👃➡️🫁",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "",
  },
  her: {
    anki: true,
    emoji: "📍⬇️",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "afto plas",
    lyk: ["hapigo", "der"],
  },
  hina: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "strela",
    kundr: ["fura"],
  },
  hir: {
    anki: true,
    emoji: "🔉➡️👂",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "zan sjkoi na corva fdu",
  },
  hiras: {
    anki: true,
    emoji: "🚄🐆⚡",
    fal: "lihko",
    falnen: "(sjiranai)",
    imi: "bruk tyd tsisai",
    kundr: ["bistra"],
  },
  hiven: {
    anki: true,
    emoji: "🍨🍦",
    fal: "tingko",
    falnen: "namting",
    kakutro: ["marojzschine", "upasnen"],
  },
  hjaku: {
    anki: true,
    emoji: "💯",
    fal: "tingko",
    falnen: "lasku",
    imi: "100 (denden)",
  },
  hjerne: {
    anki: true,
    emoji: "🧠",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  hofli: {
    anki: true,
    emoji: "🙂🙇🙏",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["kushipa"],
    tatoeba: [
      "li pashun hanu 'danke' au 'nil' au 'gomen', sore hofli. li sore hanu 'blin' au 'shaisa', sore kushipa.",
    ],
  },
  hono: {
    anki: true,
    emoji: "🔥",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  hor: {
    anki: true,
    emoji: "💇💇‍♂️💇‍♀️",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  huin: {
    anki: true,
    emoji: "🐶",
    fal: "tingko",
    falnen: "vonating",
  },
  huomi: {
    anki: true,
    emoji: "🏠🏡🏚️",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  huomilehti: {
    anki: true,
    emoji: "🏠📄",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "lehti ka du se cosce du eins se libre",
  },
  hur: {
    anki: true,
    emoji: "",
    fal: "sporko",
    falnen: "(sjiranai)",
    imi: "ka tropos? mit ka?",
  },
  hyske: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "siru dan au benj shiru ima",
    kundr: ["vasu"],
  },
  icen: {
    anki: true,
    emoji: "🤔",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "icen oba X = hur du mietta oba X",
    tatoeba: [
      "icen oba ringo: UN VIHA RINGO, un dua ringo, ringo nai bra au nai warui",
    ],
  },
  ie: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "suruko ke mangedjin bruk akote lihko os tingko cosce hej vil suruko per tingko os lihko",
  },
  ima: {
    anki: true,
    emoji: "🕰️⬇️",
    fal: "troko",
    falnen: "raz",
    imi: "afto tyd",
    lyk: ["dan", "mirai"],
  },
  imang: {
    anki: true,
    emoji: "🧲",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  imi: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
    lyk: ["tatoeba"],
    tatoeba: ["'fshto' imi 'un siru braa na hjerne fun'"],
  },
  inje: {
    anki: true,
    emoji: "📥",
    fal: "medko",
    falnen: "(sjiranai)",
    kundr: ["ecso"],
    lyk: ["mellan"],
  },
  ipkiere: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "lasku",
    imi: "1,000,000,000,000",
  },
  ipni: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "lasku",
    imi: "1,000,000",
    kakutro: ["milyon"],
  },
  iptre: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "lasku",
    imi: "1,000,000,000",
  },
  ishi: {
    anki: true,
    emoji: "🪨",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  iske: {
    anki: true,
    emoji: "🚰💧💦🌊",
    fal: "tingko",
    falnen: "glugting",
  },
  ivel: {
    anki: true,
    emoji: "🌆",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "tyd akote owari fu daag cosce daag bli naht",
  },
  jaa: {
    anki: true,
    emoji: "👋",
    fal: "hofliko",
    falnen: "(sjiranai)",
  },
  jainos: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "plasnamae",
  },
  jalaka: {
    anki: true,
    emoji: "🚶🚶‍♂️🚶‍♀️",
    fal: "suruko",
    falnen: "(sjiranai)",
    lyk: ["sjkoi"],
  },
  jam: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  jamete: {
    anki: true,
    emoji: "🛑",
    fal: "suruko",
    falnen: "(sjiranai)",
    kundr: ["benj"],
  },
  jetta: {
    anki: true,
    emoji: "✈️🛩️🛫🛬",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  joki: {
    anki: true,
    emoji: ">50%",
    fal: "atai",
    falnen: "(sjiranai)",
    lyk: ["al", "joku"],
  },
  joku: {
    anki: true,
    emoji: "",
    fal: "atai",
    falnen: "(sjiranai)",
    lyk: ["al", "joki", "nil"],
  },
  "k'": {
    anki: true,
    emoji: "",
    fal: "troko",
    falnen: "(sjiranai)",
    kakutro: ["ke"],
  },
  ka: {
    anki: true,
    emoji: "¿❓❔?",
    fal: "sporko",
    falnen: "(sjiranai)",
  },
  kaku: {
    anki: true,
    emoji: "✍️",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  kara: {
    anki: true,
    emoji: "",
    fal: "medko",
    falnen: "(sjiranai)",
    kundr: ["made"],
    tatoeba: ["pashun jalaka huomi kara = 🚶 ⬅️ 🏠"],
  },
  kase: {
    anki: true,
    emoji: "8️⃣",
    fal: "atai",
    falnen: "lasku",
  },
  katai: {
    anki: true,
    emoji: "",
    fal: "sporko",
    falnen: "lasku",
    imi: "ka atai?",
  },
  katana: {
    anki: true,
    emoji: "🔪🗡️",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  kawari: {
    anki: true,
    emoji: "🥺❤️✨",
    fal: "kokoroko",
    falnen: "(sjiranai)",
    tatoeba: ["A se 🐶.\nA: kawari!!! ❤️😍✨💖"],
  },
  kiere: {
    anki: true,
    emoji: "4️⃣",
    fal: "atai",
    falnen: "lasku",
  },
  kimo: {
    anki: false,
    emoji: "👄👎",
    fal: "lihko",
    falnen: "kokoro na aistia",
    imi: "warui na smak",
    kundr: ["oyshi"],
  },
  kini: {
    anki: true,
    emoji: "🔒🚪📪📁",
    fal: "suruko",
    falnen: "(sjiranai)",
    kundr: ["auki"],
    tatoeba: [
      "du deki jalaka na dvera auki, men du nai deki jalaka na dvera kini.",
    ],
  },
  kirain: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    lyk: ["silba", "kotoba"],
    tatoeba: ["K-I-R-A-I-N"],
  },
  kjannos: {
    anki: true,
    emoji: "文↔A",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "nasi kotoba fu ein glossa ander glossa made",
    tatoeba: ["'hello' na anglossa ie 'hola' na espanjossa"],
  },
  kjela: {
    anki: true,
    emoji: "☂️",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "ting k'du bruk grun jam pluj",
  },
  kjomi: {
    anki: true,
    emoji: "🤔",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "vil suru plus tsui jokuting",
  },
  klar: {
    anki: true,
    emoji: "🪟🧊🔍◌",
    fal: "lihko",
    falnen: "(sjiranai)",
    imi: "du deki se inje afto ting",
    kundr: ["tun"],
  },
  kntre: {
    anki: true,
    emoji: "-3",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "nil uten tre",
    tatoeba: ["kntre mit tre sama nil"],
  },
  kolarum: {
    anki: true,
    emoji: "🛌",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "rum per cola",
    tatoeba: ["du cola na kolarun"],
  },
  kompju: {
    anki: true,
    emoji: "🖥️💻",
    fal: "tingko",
    falnen: "(sjiranai)",
    lyk: ["denwa"],
  },
  kot: {
    anki: true,
    emoji: "🐱",
    fal: "tingko",
    falnen: "vonating",
    lyk: ["kotnen"],
  },
  kotnen: {
    anki: true,
    emoji: "🐱🤏",
    fal: "tingko",
    falnen: "vonating",
    imi: "neo kot, kot ka bli gvir na tyd akote",
    lyk: ["kot"],
  },
  kotoba: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "hanutro",
    lyk: ["kirain", "silba", "fras"],
  },
  kuchi: {
    anki: true,
    emoji: "👄",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  kun: {
    anki: true,
    emoji: "♀️♂️⚧︎",
    fal: "tingko",
    falnen: "kun",
  },
  kundr: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  kushipa: {
    anki: true,
    emoji: "🤪🤬🖕",
    fal: "suruko",
    falnen: "(sjiranai)",
    kundr: ["hofli"],
    tatoeba: [
      "li pashun hanu 'danke' au 'nil' au 'gomen', sore hofli. li sore hanu 'blin' au 'shaisa', sore kushipa.",
    ],
  },
  kury: {
    anki: true,
    emoji: "🌑🕶️",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["circas"],
  },
  kyajdz: {
    anki: true,
    emoji: "🥢",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  kzin: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "fami",
    imi: "lapsi fu fi",
  },
  lacsaq: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "lasku",
    imi: "10,000",
  },
  latsty: {
    anki: true,
    emoji: "⋙⋘",
    fal: "troko",
    falnen: "(sjiranai)",
    imi: "plus os minus na al",
    lyk: ["plus", "minus"],
    tatoeba: [
      "A har 🍎. B har 🍎🍎. C har 🍎🍎🍎🍎. C har lacti plus. A har lacti minus.",
    ],
  },
  lantdai: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "lant stuur ka har mange lant inje sore",
  },
  lapsi: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "fami",
    imi: "pashun ke ryodjin mahagvir",
    kundr: ["ryodjin"],
  },
  lasku: {
    anki: true,
    emoji: "🔢",
    fal: "tingko",
    falnen: "lasku",
    lyk: ["atai"],
  },
  lehti: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "punkt mange",
    lyk: ["punkt", "pisma"],
    tatoeba: ["jaa,\nima, un ergomange.\nka slucha na du?\n- sakawi kara"],
  },
  lemo: {
    anki: true,
    emoji: "🍋",
    fal: "tingko",
    falnen: "fraut",
  },
  lera: {
    anki: true,
    emoji: "🧑‍🎓",
    fal: "suruko",
    falnen: "(sjiranai)",
    kundr: ["opeta"],
  },
  lezi: {
    anki: true,
    emoji: "👀📘",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "se libre",
    lyk: ["libre"],
  },
  li: {
    anki: true,
    emoji: "",
    fal: "etuniko",
    falnen: "(sjiranai)",
    lyk: ["sit"],
    tatoeba: ["li du nai nam, sit du sjiny"],
  },
  libre: {
    anki: true,
    emoji: "📘📖📔📚",
    fal: "tingko",
    falnen: "(sjiranai)",
    lyk: ["lezi"],
  },
  lik: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
    kundr: ["tsigau"],
    lyk: ["sama"],
  },
  ljeta: {
    anki: true,
    emoji: "🪽✈️🦋🐦🪰",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "sjkoi na luft",
  },
  ljeva: {
    anki: true,
    emoji: "⬅️",
    fal: "tingko",
    falnen: "strela",
    kakutro: ["larava"],
    kundr: ["migi"],
  },
  luft: {
    anki: true,
    emoji: "💨💭☁️",
    fal: "tingko",
    falnen: "(sjiranai)",
    lyk: ["vint"],
    tatoeba: ["du treng luft na sore, os du sjiny"],
  },
  luna: {
    anki: true,
    emoji: "🌑🌕",
    fal: "tingko",
    falnen: "(sjiranai)",
    lyk: ["sol"],
  },
  luvan: {
    anki: true,
    emoji: "🥕",
    fal: "tingko",
    falnen: "ovashi",
    kakutro: ["karroqhn"],
  },
  made: {
    anki: true,
    emoji: "",
    fal: "medko",
    falnen: "(sjiranai)",
    kundr: ["kara"],
    tatoeba: ["pershun jalaka huomi made = 🏠 ⬅️ 🚶"],
  },
  magasin: {
    anki: true,
    emoji: "🏬🏪",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  mago: {
    anki: true,
    emoji: "🥭",
    fal: "tingko",
    falnen: "fraut",
  },
  maha: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  mama: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "fami",
    imi: "ryodjin onna",
    lyk: ["ryodjin", "papa"],
  },
  mange: {
    anki: true,
    emoji: "",
    fal: "lihko",
    falnen: "lasku",
    kundr: ["apar"],
  },
  maredur: {
    anki: true,
    emoji: "🐟🦈🦐🐙🦑🐬🐠",
    fal: "tingko",
    falnen: "vonating",
  },
  matetun: {
    anki: true,
    emoji: "💍",
    fal: "suruko",
    falnen: "fami",
    lyk: ["matetundjin"],
  },
  matetundjin: {
    anki: true,
    emoji: "💍🧑",
    fal: "tingko",
    falnen: "fami",
    lyk: ["matetun"],
  },
  me: {
    anki: true,
    emoji: "👁️",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  mekji: {
    anki: true,
    emoji: "👉",
    fal: "suruko",
    falnen: "(sjiranai)",
    tatoeba: [
      "🫵 hantnen mëkiiqh na du",
      "👇 hantnen mëkji na unna",
      "du mekji ting grun du vil k'anderdjin kjomi sore",
    ],
  },
  mellan: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
    lyk: ["inje"],
    tatoeba: ["2 mellan 1 au 3", "3 mellan 1 au 4", "glaubi mellan akk au nai"],
  },
  men: {
    anki: true,
    emoji: "",
    fal: "etuniko",
    falnen: "(sjiranai)",
  },
  midore: {
    anki: true,
    emoji: "🟩💚🟢",
    fal: "lihko",
    falnen: "varge",
  },
  mietta: {
    anki: true,
    emoji: "🤔💭",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "~ hanu inje hjerne fdu",
  },
  migi: {
    anki: true,
    emoji: "➡️",
    fal: "tingko",
    falnen: "(sjiranai)",
    kundr: ["ljeva"],
  },
  milenjal: {
    anki: true,
    emoji: "🥑",
    fal: "tingko",
    falnen: "ovashi",
  },
  mirairis: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "plasnamae",
    imi: "heljo nanas na pandos fun",
  },
  minus: {
    anki: true,
    emoji: "",
    fal: "troko",
    falnen: "(sjiranai)",
    kundr: ["plus"],
    lyk: ["latsty"],
  },
  mipi: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "fami",
    imi: "pershun ka har ryodjin sama",
  },
  mirai: {
    anki: true,
    emoji: "🕰️➡️",
    fal: "tingko",
    falnen: "raz",
    kundr: ["dan"],
    lyk: ["ima"],
  },
  mis: {
    anki: true,
    emoji: "🐭🐁",
    fal: "tingko",
    falnen: "vonating",
  },
  mit: {
    anki: true,
    emoji: "",
    fal: "medko",
    falnen: "(sjiranai)",
    kundr: ["uten"],
    lyk: ["bruk"],
  },
  mjes: {
    anki: true,
    emoji: "♂️👦👨👴",
    fal: "lihko",
    falnen: "kun",
  },
  mono: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "jam ting fu fal ein, na fal plusein",
    tatoeba: [
      "🍎🍎🍎🍎🍎 ru mono",
      "🍎🍎🍏🍎🍎 nai ru mono grun jam ringo midore",
    ],
  },
  mora: {
    anki: true,
    emoji: "🌅",
    fal: "tingko",
    falnen: "raz",
    imi: "tyd cosce sol bligvir",
  },
  mul: {
    anki: true,
    emoji: "🗑️",
    fal: "tingko",
    falnen: "(sjiranai)",
    lyk: ["mulbaksu"],
  },
  mulbaksu: {
    anki: true,
    emoji: "🗑️",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "ting ke du anta mul inje",
    lyk: ["mul", "baksu"],
  },
  murasace: {
    anki: true,
    emoji: "💜🟣🟪",
    fal: "lihko",
    falnen: "varge",
  },
  mus: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "lyk treng, men du nai deki sinu",
    lyk: ["treng"],
    tatoeba: ["du mus pinuno, os vi nai deki benj na jetta!"],
  },
  mwuai: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "tyd",
  },
  na: {
    anki: true,
    emoji: "",
    fal: "medko",
    falnen: "(sjiranai)",
  },
  naht: {
    anki: true,
    emoji: "🌉🌃🌑",
    fal: "tingko",
    falnen: "tyd",
  },
  nai: {
    anki: true,
    emoji: "❌",
    fal: "troko",
    falnen: "(sjiranai)",
    kundr: ["akk"],
  },
  nam: {
    anki: true,
    emoji: "🍱➡️👄",
    fal: "suruko",
    falnen: "namting",
    lyk: ["glug"],
  },
  namai: {
    anki: true,
    emoji: "📛",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  namting: {
    anki: true,
    emoji: "🍌🥭🐟🥗🥐🥖🍗🍳",
    fal: "tingko",
    falnen: "namting",
  },
  nana: {
    anki: true,
    emoji: "7️⃣",
    fal: "atai",
    falnen: "lasku",
  },
  nasi: {
    anki: true,
    emoji: "🫸",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "du mahasjkoi ting plas kara ander plas made",
  },
  naze: {
    anki: true,
    emoji: "",
    fal: "sporko",
    falnen: "(sjiranai)",
    imi: "ka grun?",
    lyk: ["grun", "perka"],
  },
  neo: {
    anki: true,
    emoji: "👶✨📱",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["gammel"],
  },
  ndofo: {
    anki: false,
    emoji: "🖐️👍",
    fal: "lihko",
    falnen: "(sjiranai)",
    imi: "bra na ryr",
    kundr: ["shblh"],
  },
  ni: {
    anki: true,
    emoji: "2️⃣",
    fal: "atai",
    falnen: "lasku",
    lyk: ["-a"],
  },
  nia: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "fami",
    imi: "lapsi fu mipi",
  },
  niden: {
    anki: true,
    emoji: "20",
    fal: "atai",
    falnen: "lasku",
    imi: "20",
  },
  nihunfraut: {
    anki: true,
    emoji: "🍒",
    fal: "tingko",
    falnen: "fraut",
  },
  nil: {
    anki: true,
    emoji: "0️⃣",
    fal: "atai",
    falnen: "lasku",
    kundr: ["al"],
    lyk: ["joku"],
  },
  nilting: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "nil ting",
  },
  niog: {
    anki: true,
    emoji: "🥥",
    fal: "tingko",
    falnen: "fraut",
  },
  nirot: {
    emoji: "🚲",
    fal: "tingko",
    falnen: "(sjiranai)",
    kakutro: ["nikrajs", "bolka"],
  },
  nitshizta: {
    anki: false,
    emoji: "😵‍💫👀👎",
    fal: "lihko",
    falnen: "kokoro na aistia",
    imi: "warui na se",
    kundr: ["helena"],
  },
  njudur: {
    anki: true,
    emoji: "🐶🐱🐘🐯🦓",
    fal: "tingko",
    falnen: "vonating",
  },
  njui: {
    anki: true,
    emoji: "💭➡️👃",
    fal: "tingko",
    falnen: "(sjiranai)",
    lyk: ["hana"],
  },
  noito: {
    anki: true,
    emoji: "🧵🧶",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  non: {
    anki: true,
    emoji: "9️⃣",
    fal: "atai",
    falnen: "lasku",
  },
  nord: {
    anki: true,
    emoji: "🧭⬆️",
    fal: "tingko",
    falnen: "strela",
  },
  oba: {
    anki: true,
    emoji: "⬆️",
    fal: "tingko",
    falnen: "strela",
    imi: "1. kundr unna; 2. tsui",
    kundr: ["unna"],
    lyk: ["tsui"],
  },
  ogoi: {
    anki: true,
    emoji: "🔊📢",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  ohare: {
    anki: true,
    emoji: "🙏🥺🥗🍱",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "vil nam",
  },
  ojogi: {
    anki: true,
    emoji: "🏊🏊‍♂️🏊‍♀️",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "sjkoi na iske",
    lyk: ["ojogidjin"],
  },
  ojogidjin: {
    anki: true,
    emoji: "🏊🏊‍♀️🏊‍♂️",
    fal: "tingko",
    falnen: "vonating",
    imi: "pashun ke ojogi",
    lyk: ["ojogi"],
  },
  onna: {
    anki: true,
    emoji: "♀︎👧👩👵",
    fal: "lihko",
    falnen: "kun",
  },
  opeta: {
    anki: true,
    emoji: "🧑‍🏫👨‍🏫👩‍🏫",
    fal: "suruko",
    falnen: "(sjiranai)",
    kundr: ["lera"],
  },
  os: {
    anki: true,
    emoji: "/",
    fal: "etuniko",
    falnen: "(sjiranai)",
  },
  ost: {
    anki: true,
    emoji: "🧭➡️",
    fal: "tingko",
    falnen: "strela",
  },
  ovashi: {
    anki: true,
    emoji: "🥗🥕🥬🫑",
    fal: "tingko",
    falnen: "ovashi",
  },
  owari: {
    anki: true,
    emoji: "🏁",
    fal: "suruko",
    falnen: "raz",
    kakutro: ["po-"],
  },
  oy: {
    anki: true,
    emoji: "📣",
    fal: "kokoroko",
    falnen: "(sjiranai)",
    tatoeba: ["A vil afto: B hyr A. A hanu: 'oy B!'"],
  },
  oyshi: {
    anki: false,
    emoji: "👄😍",
    fal: "lihko",
    falnen: "kokoro na aistia",
    imi: "braa na smak",
    kundr: ["kimo"],
  },
  paara: {
    anki: true,
    emoji: "",
    fal: "lihko",
    falnen: "(sjiranai)",
    lyk: ["praapa", "akote"],
  },
  pan: {
    anki: true,
    emoji: "🥐🥖🍞🥨",
    fal: "tingko",
    falnen: "namting",
  },
  pandos: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "plasnamae",
    imi: "pandos har sol au heljo mange. jam mange pandos",
    tatoeba: [
      "pandos fun har solh au un au du au gaja au luna au heljo mange.",
    ],
  },
  papa: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "fami",
    imi: "ryodjin mjes",
    lyk: ["ryodjin", "mama"],
  },
  paperi: {
    anki: true,
    emoji: "📰📃📄📝",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  pashun: {
    anki: true,
    emoji: "👶🧒👧👦🧑👩👨🧑‍🦱",
    fal: "tingko",
    falnen: "vonating",
    kakutro: ["-djin"],
  },
  per: {
    anki: true,
    emoji: "",
    fal: "medko",
    falnen: "(sjiranai)",
    lyk: ["perka", "grun"],
  },
  perka: {
    anki: true,
    emoji: "",
    fal: "sporko",
    falnen: "(sjiranai)",
    imi: "ka per?",
    lyk: ["per", "naze"],
  },
  persefraut: {
    anki: true,
    emoji: "🍑",
    fal: "tingko",
    falnen: "fraut",
  },
  piel: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "godja fu pashun",
    lyk: ["godja"],
  },
  piman: {
    anki: true,
    emoji: "🫑🌶️",
    fal: "tingko",
    falnen: "ovashi",
  },
  pinue: {
    anki: true,
    emoji: "🐧",
    fal: "tingko",
    falnen: "vonating",
  },
  pinuno: {
    anki: true,
    emoji: "🔇🔈",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  pisma: {
    anki: true,
    emoji: "📩",
    fal: "tingko",
    falnen: "(sjiranai)",
    lyk: ["lehti"],
  },
  pitsa: {
    anki: true,
    emoji: "🍕",
    fal: "tingko",
    falnen: "namting",
  },
  plas: {
    anki: true,
    emoji: "🏠🏞️🏔️🎑🗺️",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  plasdai: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "plas stuur",
  },
  pluj: {
    anki: true,
    emoji: "🌧️",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  plus: {
    anki: true,
    emoji: "",
    fal: "troko",
    falnen: "(sjiranai)",
    kundr: ["minus"],
    lyk: ["latsty"],
  },
  pojk: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "fami",
  },
  portocale: {
    anki: true,
    emoji: "🍊🟧🧡🟠",
    fal: ["tingko", "lihko"],
    falnen: ["fraut", "varge"],
    imi: "1. fraut 🍊; 2. varge 🟧🧡🟠",
  },
  posaidis: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "plasnamae",
    imi: "heljo kases na pandos fun",
  },
  praapa: {
    anki: true,
    emoji: "",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["akote"],
    lyk: ["paara"],
  },
  pranvera: {
    anki: true,
    emoji: "🌹⛅🌱☔",
    fal: "tingko",
    falnen: "toshitel",
    imi: "toshitel ke mwuai 3s au 4s au 5s inje",
  },
  prapataj: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  pravda: {
    anki: true,
    emoji: "✅",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["uso"],
  },
  protofugel: {
    anki: true,
    emoji: "🦕🦖",
    fal: "tingko",
    falnen: "vonating",
  },
  punkt: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    lyk: ["fras", "lehti"],
  },
  ranja: {
    anki: true,
    emoji: "🫚",
    fal: "tingko",
    falnen: "vonating",
    tatoeba: ["baum har ranha unna ter"],
  },
  ranjako: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "hanutro",
    imi: "li jam festako lyk kotobanen, kotobastuur ie ranjako.",
    tatoeba: [
      "inje ko 'amerikalant', jam ranjako 'amerika' au kotobanen 'lant'",
    ],
  },
  raz: {
    anki: true,
    emoji: "🕰️",
    fal: "tingko",
    falnen: "raz",
    imi: "katai suru",
    tatoeba: [
      "un hanu ni raz. un 🗣️. un 🗣️.",
      "un hanu kiere raz. un 🗣️. un 🗣️. un 🗣️. un 🗣️.",
    ],
  },
  ri: {
    anki: true,
    emoji: "",
    fal: "medko",
    falnen: "(sjiranai)",
    imi: "ting suru ka?",
    lyk: ["te", "wa"],
    tatoeba: ["un nam ringo", "un te ringo ri nam"],
  },
  ringo: {
    anki: true,
    emoji: "🍎🍏",
    fal: "tingko",
    falnen: "fraut",
  },
  rinj: {
    anki: true,
    emoji: "📞",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  riso: {
    anki: true,
    emoji: "🖼️",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  rjoho: {
    anki: true,
    emoji: "",
    fal: "atai",
    falnen: "(sjiranai)",
    imi: "al hej",
    tatoeba: ["A: du vil cafe os iske?\nB: un vil cafe AU iske! un vil rjoho!"],
  },
  roza: {
    anki: true,
    emoji: "🩷💗🎀",
    fal: "lihko",
    falnen: "varge",
  },
  ru: {
    anki: true,
    emoji: "🔴🟥❤️",
    fal: "lihko",
    falnen: "varge",
  },
  rum: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  ruma: {
    anki: false,
    emoji: "👂👎",
    fal: "lihko",
    falnen: "kokoro na aistia",
    imi: "warui na hyr",
    kundr: ["wavu"],
  },
  ryodjin: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "fami",
    imi: "mama au papa. ryodjin fu du maha du. du vona ryodjin kara.",
    kundr: ["lapsi"],
    lyk: ["mama", "papa"],
  },
  ryr: {
    anki: true,
    emoji: "🖐️",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "aistia mit hant",
    lyk: ["hant"],
  },
  rzinzai: {
    anki: true,
    emoji: "🏃🏃‍♂️🏃‍♀️",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "jalaka mit tyd tsisai",
  },
  sakana: {
    anki: true,
    emoji: "🐟🐠",
    fal: "tingko",
    falnen: "vonating",
  },
  sakawi: {
    anki: true,
    emoji: "",
    fal: "namae",
    falnen: "vonating",
    imi: "mahadjin fu afto kotoli",
  },
  sama: {
    anki: true,
    emoji: "",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["tsigau"],
    lyk: ["lik"],
  },
  samui: {
    anki: true,
    emoji: "🥶🧊❄️",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["vapa"],
  },
  sawi: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "fami",
    imi: "matetundjin fu lapsi os mipi",
  },
  scecso: {
    anki: true,
    emoji: "📤🚶",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "sjkoi ecso made, sjkoi her kara",
    kundr: ["sceer"],
  },
  sceer: {
    anki: true,
    emoji: "📥🚶",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "sjkoi her made",
    kundr: ["scecso"],
  },
  sdanie: {
    anki: true,
    emoji: "🏠🏬🏢⛪",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  se: {
    anki: true,
    emoji: "👀",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  sentaku: {
    anki: true,
    emoji: "🤔💬",
    fal: "suruko",
    falnen: "(sjiranai)",
    tatoeba: [
      'A: du vil ros ringo os midori ringo?\nB: un sentaku ros, sitte un vil ringo ros.\n"un sentaku A" likk "li mono A os B, un vil A"',
    ],
  },
  shblh: {
    anki: false,
    emoji: "🖐️👎",
    fal: "lihko",
    falnen: "kokoro na aistia",
    imi: "warui na ryr",
    kundr: ["ndofo"],
  },
  shiro: {
    anki: true,
    emoji: "🤍⚪⬜🏳️",
    fal: "lihko",
    falnen: "varge",
    kundr: ["curo"],
  },
  shirutro: {
    anki: true,
    emoji: "🧫🧪🧬🔬",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "tropos per siru",
  },
  sho: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "tyd",
  },
  siha: {
    anki: true,
    emoji: "🐱🐟",
    fal: "lihko",
    falnen: "(sjiranai)",
    imi: "afto naideki sjinu du",
    kundr: ["cris"],
    tatoeba: ["🦈 cris. 🐱 siha."],
  },
  silba: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "hanutro",
    lyk: ["kirain", "kotoba"],
  },
  simpel: {
    anki: true,
    emoji: "",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["haaste"],
  },
  sini: {
    anki: true,
    emoji: "🩵",
    fal: "lihko",
    falnen: "varge",
  },
  siru: {
    anki: true,
    emoji: "📥🧠",
    fal: "suruko",
    falnen: "(sjiranai)",
    lyk: ["fshto"],
  },
  sisco: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "fami",
  },
  sit: {
    anki: true,
    emoji: "",
    fal: "troko",
    falnen: "(sjiranai)",
    lyk: ["li"],
    tatoeba: ["li du nai glug iske, sit du sinu ☠️"],
  },
  sjikno: {
    anki: true,
    emoji: "🍲🦵👨‍🦰",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  sjinu: {
    anki: true,
    emoji: "☠️💀😵⚰️🪦",
    fal: "suruko",
    falnen: "(sjiranai)",
    kundr: ["vona"],
    lyk: ["utenvona"],
  },
  skhola: {
    anki: true,
    emoji: "🏫",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  sjkoi: {
    anki: true,
    emoji: "🚶‍♀️✈️🚝🚴🚘🚀🏊",
    fal: "suruko",
    falnen: "(sjiranai)",
    lyk: ["aja", "jalaka"],
  },
  skwalo: {
    anki: true,
    emoji: "🦈",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  slucha: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "~ suru ke jam",
    kakutro: ["hlutsza"],
    tatoeba: [
      "A: ka slucha na du?\nB: un braa! danki, au na du?\nA: un bra auen!",
    ],
  },
  smak: {
    anki: true,
    emoji: "👅",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "aistia mit glossa",
    lyk: ["glossa"],
    tatoeba: [
      "du smak mit glossa(👅). du se(👀) mit me(👁️). du hyr mit corva.",
    ],
  },
  sol: {
    anki: true,
    emoji: "🌞☀️",
    fal: "tingko",
    falnen: "(sjiranai)",
    lyk: ["luna"],
  },
  sore: {
    anki: true,
    emoji: "",
    fal: "pashko",
    falnen: "pashko",
    lyk: ["hej"],
  },
  sot: {
    anki: true,
    emoji: "🧁🍩🎂🍦🍯🍡🍭",
    fal: "lihko",
    falnen: "(sjiranai)",
  },
  spara: {
    anki: true,
    emoji: "⬇️",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "sjkoi unna made",
  },
  spil: {
    anki: true,
    emoji: "🎲🏏🎮👾🎳🎰🀄",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  spor: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    kundr: ["svar"],
  },
  sporko: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "spor kotoba",
    tatoeba: ["ka?", "naze?", "dare?", "doko?"],
  },
  stift: {
    anki: true,
    emoji: "🖊️🖋️",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "tropos per kaku",
  },
  strela: {
    anki: true,
    emoji: "←↖↓↔⇅",
    fal: "tingko",
    falnen: "strela",
  },
  stuur: {
    anki: true,
    emoji: "",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["tsisai"],
  },
  sud: {
    anki: true,
    emoji: "🧭⬇️",
    fal: "tingko",
    falnen: "strela",
  },
  sukha: {
    anki: true,
    emoji: "👀🏹",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  suksu: {
    anki: true,
    emoji: "🍂🍁🎃",
    fal: "tingko",
    falnen: "toshitel",
  },
  suru: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "hanutro",
    lyk: ["suruko"],
  },
  suruko: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "hanutro",
    imi: "kotoba per suru",
    lyk: ["suru"],
    tatoeba: ["rzinsai", "sjkoi", "nam", "nasi", "maha"],
  },
  surujna: {
    anki: true,
    emoji: "",
    fal: "lihko",
    falnen: "hanutro",
    imi: "suru yena",
  },
  svar: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "hanutro",
    kundr: ["spor"],
  },
  tajka: {
    anki: true,
    emoji: "✨🧙🪄",
    fal: "lihko",
    falnen: "(sjiranai)",
  },
  tajkadzin: {
    anki: true,
    emoji: "🧙🧙‍♀️🧙‍♂️",
    fal: "tingko",
    falnen: "vonating",
    imi: "pashun ka deki tajka",
  },
  tak: {
    anki: true,
    emoji: "",
    fal: "medko",
    falnen: "(sjiranai)",
    imi: "1. na afto tropos; 2. mange MANGE",
  },
  talvi: {
    anki: true,
    emoji: "❄️🏔️⛷️🧤",
    fal: "tingko",
    falnen: "toshitel",
  },
  tasti: {
    anki: true,
    emoji: "🖱️👆",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  tatoeba: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    lyk: ["imi"],
    tatoeba: ["tatoeba fu pershunn: 🧑🧓🫅👳🧑‍🦰", "tatoeba fu ringo: 🍎🍏"],
  },
  te: {
    anki: true,
    emoji: "",
    fal: "medko",
    falnen: "(sjiranai)",
    imi: "ka suru ting?",
    lyk: ["ri", "wa"],
    tatoeba: ["un nam ringo", "un te ringo ri nam"],
  },
  tel: {
    anki: true,
    emoji: "",
    fal: "lihko",
    falnen: "(sjiranai)",
    imi: "al fu afto ting",
    kundr: ["hel"],
    tatoeba: ["🎂 hel torta. 🍰 tel torta."],
  },
  ter: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "ting k'joki baum vona na",
  },
  terbi: {
    anki: true,
    emoji: "📺",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  ting: {
    anki: true,
    emoji: "🔮🥒🐀🧠🎂🫀🚽🎁",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  torta: {
    anki: true,
    emoji: "🧁🎂🍰",
    fal: "tingko",
    falnen: "namting",
  },
  toshitel: {
    anki: true,
    emoji: "❄️🌹🌞🍂",
    fal: "tingko",
    falnen: "toshitel",
    imi: "~ tre mwuai",
  },
  tosui: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "tyd",
  },
  tre: {
    anki: true,
    emoji: "3️⃣",
    fal: "atai",
    falnen: "lasku",
  },
  treng: {
    anki: true,
    emoji: "💀",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "mus, os du sjinu",
    lyk: ["mus"],
  },
  trict: {
    anki: true,
    emoji: "😭😢😥",
    fal: "lihko",
    falnen: "kokoro",
  },
  tropos: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  tsatain: {
    anki: true,
    emoji: "🎯",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["tun"],
  },
  tsigau: {
    anki: true,
    emoji: "",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["sama", "lik"],
  },
  tsisai: {
    anki: true,
    emoji: "🤏",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["stuur"],
  },
  tsui: {
    anki: true,
    emoji: "",
    fal: "medko",
    falnen: "(sjiranai)",
    lyk: ["oba"],
  },
  tualet: {
    anki: true,
    emoji: "🚽",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  tuhat: {
    anki: true,
    emoji: "",
    fal: "atai",
    falnen: "lasku",
    imi: "1000",
  },
  tulla: {
    anki: true,
    emoji: "🧑➡️🚪",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  tun: {
    anki: true,
    emoji: "",
    fal: "lihko",
    falnen: "(sjiranai)",
    imi: "1. kundr klar; 2. kundr tsatain",
    kundr: ["klar", "tsatain"],
  },
  tuo: {
    anki: true,
    emoji: "",
    fal: "atai",
    falnen: "(sjiranai)",
    lyk: ["afto", "asoko"],
  },
  tutr: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "fami",
  },
  tyd: {
    anki: true,
    emoji: "🕰️⏳⏰⌚",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  ufne: {
    anki: true,
    emoji: "⏺️🎦",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  un: {
    anki: true,
    emoji: "",
    fal: "pashko",
    falnen: "pashko",
    lyk: ["vi"],
  },
  unna: {
    anki: true,
    emoji: "⬇️",
    fal: "tingko",
    falnen: "strela",
    kundr: ["oba"],
  },
  uno: {
    anki: true,
    emoji: "",
    fal: "sporko",
    falnen: "(sjiranai)",
    imi: "ka suru?",
    tatoeba: ["A: uno huin?\nB: huin maha huomi."],
  },
  uslova: {
    anki: true,
    emoji: "🤝🤔💭🟰",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "mietta na sama",
    tatoeba: [
      `A: un dua kot!
B: un dua kot awen!
A au B uslova ka hej dua kot.`,
    ],
  },
  uso: {
    anki: true,
    emoji: "❌",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["pravda"],
  },
  uten: {
    anki: true,
    emoji: "",
    fal: "medko",
    falnen: "(sjiranai)",
    imi: "mit nai",
    kundr: ["mit"],
  },
  utenvona: {
    anki: true,
    emoji: "🪨🎸🚀",
    fal: "lihko",
    falnen: "(sjiranai)",
    imi: "ting ke nai deki vona au nai deki sjinu",
    kundr: ["vona"],
    lyk: ["sjinu"],
  },
  uuk: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "tyd",
    imi: "daag nana",
  },
  uwaki: {
    anki: true,
    emoji: "❌🚫⛔",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "kjannos na viocca",
  },
  valtsa: {
    anki: true,
    emoji: "💃🕺",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  vapa: {
    anki: true,
    emoji: "🥵🔥",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["samui"],
  },
  varge: {
    anki: true,
    emoji: "🎨❤️💚🟨🔷🟧🔴🟩",
    fal: "tingko",
    falnen: "varge",
  },
  vasu: {
    anki: true,
    emoji: "🫥🧠",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "shiru dan men nai shiru ima",
    kundr: ["hyske"],
  },
  vauva: {
    anki: true,
    emoji: "👶",
    fal: "tingko",
    falnen: "vonating",
  },
  velt: {
    anki: true,
    emoji: "🌎🗺️🌐",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  vera: {
    anki: true,
    emoji: "☀️😎🏄‍♂️🏖️",
    fal: "tingko",
    falnen: "toshitel",
  },
  vet: {
    anki: true,
    emoji: "🫁",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  vi: {
    anki: true,
    emoji: "",
    fal: "pashko",
    falnen: "pashko",
    imi: "un mange",
    lyk: ["un"],
  },
  viha: {
    anki: true,
    emoji: "😡",
    fal: "lihko",
    falnen: "kokoro",
    kundr: ["dua"],
  },
  vint: {
    anki: true,
    emoji: "💨💭☁️",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "jam vint cosce luft sjkoi",
    lyk: ["luft"],
  },
  vikoli: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "libre fu viossa na kompjusiru",
    tatoeba: ["https://vikoli.org"],
  },
  vikti: {
    anki: false,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
    tatoeba: [
      "li glugnaj iskıë, du shiny. glug iskıë vichti!!!",
      "vill'd iskıe oß kÿophi? eee vichtinaj, rjoho braa n'unn",
    ],
  },
  vil: {
    anki: true,
    emoji: "",
    fal: "suruko",
    falnen: "(sjiranai)",
  },
  vinjafraut: {
    anki: true,
    emoji: "🍇",
    fal: "tingko",
    falnen: "fraut",
    kakutro: ["uva"],
  },
  viossa: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "glossa fu vi",
    tatoeba: ["afto viossa!"],
  },
  vona: {
    anki: true,
    emoji: "🌺🧒🦋",
    fal: "tingko",
    falnen: "vonating",
    kundr: ["sjinu", "utenvona"],
  },
  vrach: {
    anki: true,
    emoji: "🧑‍⚕️👩‍⚕️👨‍⚕️",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "pashun ka ergo na bjurkiplas",
  },
  vulcanis: {
    anki: true,
    emoji: "",
    fal: "tingko",
    falnen: "plasnamae",
    imi: "",
  },
  wa: {
    anki: true,
    emoji: "",
    fal: "medko",
    falnen: "(sjiranai)",
    imi: "ka suru ting?",
    lyk: ["ri", "te"],
    tatoeba: ["huin ie blau", "huin wa blau ie"],
  },
  warui: {
    anki: true,
    emoji: "👎",
    fal: "lihko",
    falnen: "(sjiranai)",
    kundr: ["bra"],
  },
  wavu: {
    anki: false,
    emoji: "👂👍",
    fal: "lihko",
    falnen: "kokoro na aistia",
    imi: "bra na hyr",
    kundr: ["ruma"],
  },
  we: {
    anki: true,
    emoji: "",
    fal: "troko",
    falnen: "(sjiranai)",
    imi: "akk os nai?",
    tatoeba: [
      "A: du har huin we?\nB: un har huin, akk.\nA: braa. un dua huin.",
    ],
  },
  west: {
    anki: true,
    emoji: "🧭⬅️",
    fal: "tingko",
    falnen: "strela",
  },
  ze: {
    anki: true,
    emoji: "🕰️",
    fal: "medko",
    falnen: "tyd",
    kundr: ["de"],
    tatoeba: ["un nam ze glug. eins, un glug. nis (ima), un nam."],
  },
  zedvera: {
    anki: true,
    emoji: "🔗",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "dvera ka du deki bruk per sjkoi na kompjusiru",
    tatoeba: ["https://vikoli.org/huomilehti"],
  },
  zehant: {
    anki: true,
    emoji: "🖱️",
    fal: "tingko",
    falnen: "(sjiranai)",
    imi: "hant zeus ke du bruk na kompju",
  },
  zeme: {
    anki: true,
    emoji: "📸🎥📷",
    fal: "tingko",
    falnen: "(sjiranai)",
  },
  zespil: {
    anki: true,
    emoji: "🎮",
    fal: "suruko",
    falnen: "(sjiranai)",
    imi: "spil na kompju",
  },
  zeus: {
    anki: true,
    emoji: "⚡",
    fal: "tingko",
    falnen: "(sjiranai)",
    kakutro: ["ze-"],
  },
}

const kotobasirupravda: Record<string, WordData> = Object.fromEntries(
  Object.entries(kotobasirumahena)
    .flatMap<[string, WordData]>(([key, value]) => [
      [key, { ...value, eins: true }],
      ...(value.kakutro?.map(
        (kotoba) =>
          [
            kotoba,
            {
              ...value,
              kakutro: value
                .kakutro!.filter((x) => x != kotoba)
                .concat(key)
                .sort(sortWords),
              eins: false,
            },
          ] satisfies [string, WordData],
      ) || []),
    ])
    .sort(sortPairs),
)
